"""
Django settings for solicitudes_vn project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+i9ta-c_3%vzr_l=1)b9pg^74e6%mx1d!7!n(@rd@85_5wt-0a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'solicitudes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'solicitudes.middleware.ErrorMiddleware',
]

ROOT_URLCONF = 'solicitudes_vn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'solicitudes_vn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'solicitudes_escolares',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'solicitudes' / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Email configuration
# Uses Flask-style MAIL_* environment variables when available.
ENV_FILE = BASE_DIR / '.env'
if ENV_FILE.exists():
    try:
        from dotenv import load_dotenv

        load_dotenv(dotenv_path=ENV_FILE)
    except ImportError:
        pass

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('MAIL_SERVER', 'smtp.gmail.com').strip()
EMAIL_PORT = int(os.environ.get('MAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('MAIL_USE_TLS', 'True').strip().lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.environ.get('MAIL_USE_SSL', 'False').strip().lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('MAIL_USERNAME', '')
if isinstance(EMAIL_HOST_USER, str):
    EMAIL_HOST_USER = EMAIL_HOST_USER.strip()

# Some exported env files may include accidental spaces in passwords (copied from GUI).
# Remove spaces around/inside the password so Gmail app-passwords keep working.
EMAIL_HOST_PASSWORD = os.environ.get('MAIL_PASSWORD', '')
if isinstance(EMAIL_HOST_PASSWORD, str):
    EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD.strip().replace(' ', '')

DEFAULT_FROM_EMAIL = f"Solicitudes VN <{EMAIL_HOST_USER}>"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Convenience flag: True when we have credentials to send real emails.
EMAIL_ENABLED = bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)

# Quick debug output when Django starts (useful for diagnosing SMTP issues).
try:
    print('EMAIL_ENABLED=', EMAIL_ENABLED, 'EMAIL_HOST=', EMAIL_HOST, 'EMAIL_PORT=', EMAIL_PORT, 'EMAIL_USE_TLS=', EMAIL_USE_TLS, 'EMAIL_USE_SSL=', EMAIL_USE_SSL, 'EMAIL_HOST_USER=', EMAIL_HOST_USER)
except Exception:
    pass
